### ISSUE TITLE
rename repository

### ISSUE THREAD

**Issue by professor-enoqueleal** [EduardoXerxenevsky/qualiset#1]
Por favor fazer o _rename_ do repositório.

Para o nome de repositório, seguir a convenção onde todas as letras devem ser minúsculas e as palavras separadas com hífen no padrão _kebab-case_ https://coodesh.com/blog/candidates/dicas/convencoes-de-codificacao-do-camelcase-ao-kebab-case/

**Comment by EduardoXerxenevsky** [comment]
rename feito de acordo com o padrão _kebab-case_
